# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param chipscope.maxJobs 1
create_project -in_memory -part xc7a35tcpg236-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/dimple/Downloads/Fourth_Year_First_Semester/EE789/project_5/project_5.cache/wt [current_project]
set_property parent.project_path /home/dimple/Downloads/Fourth_Year_First_Semester/EE789/project_5/project_5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/dimple/Downloads/Fourth_Year_First_Semester/EE789/project_5/project_5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library ahir_ieee_proposed /home/dimple/Downloads/Fourth_Year_First_Semester/EE789/project_5/project_5.srcs/sources_1/imports/Downloads/Fourth_Year_First_Semester/EE789/release/vhdl/aHiR_ieee_proposed.vhdl
read_vhdl -library ahir /home/dimple/Downloads/Fourth_Year_First_Semester/EE789/project_5/project_5.srcs/sources_1/imports/Downloads/Fourth_Year_First_Semester/EE789/release/vhdl/ahir.vhdl
read_vhdl -library xil_defaultlib {
  /home/dimple/Downloads/Fourth_Year_First_Semester/EE789/project_5/project_5.srcs/sources_1/imports/Downloads/ahir_system_global_package.vhdl
  /home/dimple/Downloads/Fourth_Year_First_Semester/EE789/project_5/project_5.srcs/sources_1/imports/Downloads/ahir_system.vhdl
  /home/dimple/Downloads/Fourth_Year_First_Semester/EE789/project_5/project_5.srcs/sources_1/imports/Downloads/Fourth_Year_First_Semester/EE789/processor/processor1/addons/uart/simpleUartLib.vhdl
  /home/dimple/Downloads/Fourth_Year_First_Semester/EE789/project_5/project_5.srcs/sources_1/imports/Downloads/Fourth_Year_First_Semester/EE789/post-mid/basys3_bundle_for_ee789/basys3_top_vhdl/basys3_top.vhdl
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/dimple/Downloads/Fourth_Year_First_Semester/EE789/project_5/project_5.srcs/constrs_1/imports/constraint/basys3.xdc
set_property used_in_implementation false [get_files /home/dimple/Downloads/Fourth_Year_First_Semester/EE789/project_5/project_5.srcs/constrs_1/imports/constraint/basys3.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top basys3_top -part xc7a35tcpg236-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef basys3_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file basys3_top_utilization_synth.rpt -pb basys3_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
